-- Align enums with prisma schema
ALTER TYPE "SettlementMethod" ADD VALUE IF NOT EXISTS 'PHYSICAL';
ALTER TYPE "SettlementMethod" ADD VALUE IF NOT EXISTS 'MIXED';
ALTER TYPE "AccountTxType" ADD VALUE IF NOT EXISTS 'REMITTANCE';
ALTER TYPE "DepositStatus" ADD VALUE IF NOT EXISTS 'REVERSED';
ALTER TYPE "WithdrawStatus" ADD VALUE IF NOT EXISTS 'REVERSED';
ALTER TYPE "TradeStatus" ADD VALUE IF NOT EXISTS 'CANCELLED_BY_USER';
ALTER TYPE "TradeStatus" ADD VALUE IF NOT EXISTS 'CANCELLED_BY_ADMIN';
-- Ensure TradeType exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'TradeType') THEN
        CREATE TYPE "TradeType" AS ENUM ('SPOT', 'TOMORROW', 'DAY_AFTER');
    END IF;
END $$;
